
function volunteers() {
    return [ {
        'Timestamp': '1/12/2019 11:02:40',
        'Name': 'Colleen Nhim',
        'Email': 'colleennhim@gmail.com',
        'Phone number': '5039847722',
        'Zip Code': '97201',
        'Miles': '5 miles',
        'Do you have a car?': 'Yes',
        'Do you want to work with kids?': 'Yes',
        'Can you pass a background check?': 'Maybe',
        'Please select any program area that interests you': 'Refugee Career Pathways Program, Youth',
        'What times are you available? [Monday]': '',
        'What times are you available? [Tuesday]': 'Morning',
        'What times are you available? [Wednesday]': 'Midday',
        'What times are you available? [Thursday]': 'Midday',
        'What times are you available? [Friday]': '',
        'What times are you available? [Saturday]': '',
        'What times are you available? [Sunday]': '',
        'Please submit your cover letter or resume':
        'https://drive.google.com/open?id=1B_ABr6qY1T7Dcywye73K6eeTlzSwPlOW' },
    {
        'Timestamp': '1/12/2019 11:04:24',
        'Name': 'Bob Johnson',
        'Email': 'bobjohnson@gmail.com',
        'Phone number': '9712237584',
        'Zip Code': '97007',
        'Miles': '20+ miles',
        'Do you have a car?': 'No',
        'Do you want to work with kids?': 'Maybe',
        'Can you pass a background check?': 'Maybe',
        'Please select any program area that interests you': 'Employment and Training Services',
        'What times are you available? [Monday]': 'Afternoon',
        'What times are you available? [Tuesday]': '',
        'What times are you available? [Wednesday]': '',
        'What times are you available? [Thursday]': '',
        'What times are you available? [Friday]': '',
        'What times are you available? [Saturday]': 'Afternoon',
        'What times are you available? [Sunday]': 'Afternoon',
        'Please submit your cover letter or resume': '' },
    {
        'Timestamp': '1/12/2019 11:05:39',
        'Name': 'Lily Name',
        'Email': 'lilyname@yahoo.com',
        'Phone number': '3248889605',
        'Zip Code': '971011',
        'Miles': '15 miles',
        'Do you have a car?': 'No',
        'Do you want to work with kids?': 'No',
        'Can you pass a background check?': 'No',
        'Please select any program area that interests you': 'Development, Refugee Career Pathways Program',
        'What times are you available? [Monday]': '',
        'What times are you available? [Tuesday]': '',
        'What times are you available? [Wednesday]': '',
        'What times are you available? [Thursday]': '',
        'What times are you available? [Friday]': '',
        'What times are you available? [Saturday]': 'Morning, Midday, Afternoon',
        'What times are you available? [Sunday]': 'Morning, Midday, Afternoon',
        'Please submit your cover letter or resume': '' } ]
}

export default volunteers;